assistant/assistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contacts/", include("contacts.urls")),
    path("docs/", include("docs.urls")),
    path("", include("news.urls")),
    # path("notes/", include("notes.urls")),
    path("users/", include("users.urls")),
]

assistant/docs/urls.py
from django.urls import path
from . import views

app_name = 'docs'

urlpatterns = [
    path('user_files/', views.user_files, name='user_files'),
    path('rename/', views.rename_file, name='rename_file'),
    path('delete/', views.delete_file, name='delete_file'),
]

assistant/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("", views.main, name="root"),
    path("news/", views.news_list, name="news_list"),
    path("news_ua/", views.news_list_ua_main, name="news_ua"),
    path("news_ua/", views.detail, name="detail_news"),
    path("news_ua/", views.news_list_ua_war, name="war"),
    path("news_ua/", views.news_list_ua_society, name="society"),
    path("news_ua/", views.news_list_ua_world, name="world"),
    path("news_ua/", views.news_list_ua_science, name="science"),
    path("news_ua/", views.news_list_ua_economics, name="economics"),
    path("news_ua/sport", views.news_list_ua_sport, name="sport"),

]

assistant/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signin/", RegisterView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"
    ),
    path("reset-password/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

assistant/news/models.py
from django.db import models


class Topic(models.Model):
    name = models.CharField()


class News(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    url = models.CharField()
    published_at = models.CharField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

assistant/news/views.py
from django.shortcuts import render, redirect
import requests
from django.conf import settings
# from .models import News, Topic

import json


# Create your views here.
def main(request):
    return render(request, "news/index.html", {})


def get_news(category='general'):
    url = 'https://newsapi.org/v2/top-headlines'
    parameters = {
        'country': 'us',
        'category': category,
        'apiKey': settings.NEWSAPI_KEY,
    }
    response = requests.get(url, params=parameters)
    data = response.json()
    return data['articles']

def news_list(request):
    news_data = get_news()
    context = {
        'news': news_data
    }
    return render(request, 'news/news_list.html', context)

def fetch_news():
    url = "https://newsapi.org/v2/top-headlines?country=us&apiKey=" + settings.NEWSAPI_KEY
    response = requests.get(url)
    if response.status_code == 200:
        return response.json().get('articles', [])[:5]  # обмежуємо кількість новин до 5
    return []



# def create_topics_news():

#     Topic.objects.all().delete()
#     News.objects.all().delete()

#     # news_data = articles_scraped

#     with open("./data.json", "r", encoding="utf-8") as fl:

#         topic_news = json.load(fl)

#     for key, value in topic_news:
#         Topic.objects.create(
#             name = key
#         )
#         topic_id, data = Topic.objects.get_or_create(name=key)
#         for el in value:
#             News.objects.create(
#                 title = el['title'],
#                 description =el['content'],
#                 url = el['url'],
#                 published_at = el['date'],
#                 topic = topic_id
#                 )

    # return redirect(to="news:news_ua")


def news_list_ua_for_topic(topic: str):
    news_list = []
    with open("./data.json", "r", encoding="utf-8") as fl:

       list_news = json.load(fl)
    for el in list_news:
        context = {
        'news': list_news[topic]
    }
    return context

def news_list_ua_main(request):
    context = news_list_ua_for_topic(topic="main")
    return render(request, 'news/news_ua.html', context)

def news_list_ua_war(request):
    context = news_list_ua_for_topic("war")
    return render(request, 'news/news_ua.html', context)

def news_list_ua_society(request):
    context = news_list_ua_for_topic(topic="society")
    return render(request, 'news/news_ua.html', context) 

def news_list_ua_world(request):
    context = news_list_ua_for_topic(topic="world")
    return render(request, 'news/news_ua.html', context)  

def news_list_ua_economics(request):
    context = news_list_ua_for_topic(topic="economics")
    return render(request, 'news/news_ua.html', context)

def news_list_ua_science(request):
    context = news_list_ua_for_topic(topic="science")
    return render(request, 'news/news_ua.html', context)

def news_list_ua_sport(request):
    context = news_list_ua_for_topic(topic="sport")
    return render(request, 'news/news_ua.html', context)    

def detail(request):
    pass

# <h2>News List</h2>

# <ul>
#     {% for item in news %}
#     <li>
#         <strong><a href="{{ item.url }}" target="_blank">{{ item.title }}</a></strong>
#         <p>{{ item.description }}</p>
#         <small>Published at: {{ item.published_at}}</small>
#     </li>
#     {% endfor %}
# </ul>

assistant/news/templates/news/article_content.html
{% extends "news/base.html" %}

{% block content %}

<h4>{{ author.fullname }}</h4>
<p>was born on : {{ author.born_date }} in {{ author.born_location }}</p>
<p>About author: {{ author.description }}</p>
class News(models.Model):
title = models.CharField(max_length=200)
description = models.TextField()
url = models.URLField()
published_at = models.DateTimeField()

{% endblock %}

assistant/news/templates/news/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'news/style.css' %}" />
    <title>{% trans "Put Here Your Title" %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">{% trans "Hello World!" %}</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'news:news_list' %}">{% trans "News" %}</a>
            </li>
            <li>
              <a class="nav-link" href="{% url 'news:news_ua' %}">{% trans "News_ua" %}</a>
            </li>             
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'docs:user_files' %}">{% trans "User Files" %}</a>
            </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
            <!-- Language Dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Language" %}
              </a>
              <ul class="dropdown-menu" aria-labelledby="languageDropdown">
                <li><a class="dropdown-item" href="?lang=en">{% trans "English" %}</a></li>
                <li><a class="dropdown-item" href="?lang=uk">{% trans "Українська" %}</a></li>
                <!-- Add more languages as needed -->
              </ul>
            </li>
            <!-- End Language Dropdown -->

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% trans "Welcome" %}, {{ user.username }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'news:news_list' %}">{% trans "News" %}</a></li>
                <li><a class="dropdown-item" href="{% url 'docs:user_files' %}">{% trans "User Files" %}</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">{% trans "Logout" %}</a></li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">{% trans "Login" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">{% block content %} {% endblock %}</div>
    </div>
    <!-- Доданий Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  </body>
</html>

assistant/news/templates/news/index.html
{% extends 'news/base.html'%} {% block content %}

<div class="col-md-8">
</div>
{% endblock %}

assistant/news/templates/news/news_list.html
{% extends "news/base.html" %}

{% block content %}
  <h2>News List</h2>
  
  <ul>
    {% for item in news %}
      <li>
        <strong><a href="{{ item.url }}" target="_blank">{{ item.title }}</a></strong>
        <p>{{ item.description }}</p>
        <small>Published at: {{ item.published_at|date:"F d, Y" }}</small>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

assistant/news/templates/news/news_ua.html
{% extends "news/base.html" %}

{% block content %}
<h2>Новини</h2>
<table table-layout: fixed;>
    <tr>
    <td width:100%;><a name="main" href="{% url 'news:news_ua'%}">Головні новини дня</a></td>
    <td width:100%;><a name="war" href="{% url 'news:war'%}">Війна</a></td>
    <td width:100%;><a name="world" href="{% url 'news:world'%}">Світові новини</a></td>
    <td width:100%;><a name ="society" href="{% url 'news:society'%}">Новини України</a></td>
    <td width:100%;><a name="economis" href="{% url 'news:economics'%}">Економіка</a></td>
    <td width:100%;><a name=" science" href="{% url 'news:science'%}">Наука</a></td>
    <td width:100%;><a name="sport" href="{% url 'news:sport'%}">Спорт</a></td>
    </tr>
</table>
<ul>
    {% for item in news %}
    <li>
        <!-- href="{% url 'news:news_ua'%}" -->
        <strong><a href="{{ item.url }}" target="_blank">{{ item.title }}</a></strong>
        <p>{{ item.content }}</p>
        <small>Published at: {{ item.date}}</small>
    </li>
    {% endfor %}
</ul>

{% endblock %}